name: flutter_riverpod_to_do_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.5.3
  firebase_core: ^2.10.0
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  state_notifier: ^0.7.2+1
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  json_serializable: ^6.6.2


flutter:


  uses-material-design: true


